dist: xenial
sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.4
      env: TOXENV=py34-dj20
    - python: 3.5
      env: TOXENV=py35-dj20
    - python: 3.6
      env: TOXENV=py36-dj20
    - python: 3.7
      env: TOXENV=py37-dj20
    - python: 3.5
      env: TOXENV=py35-dj21
    - python: 3.6
      env: TOXENV=py36-dj21
    - python: 3.7
      env: TOXENV=py37-dj21

install:
  - pip install tox codecov
script:
  - tox -v
after_success:
  - codecov
