dist: xenial

language: python

cache: pip

matrix:
  fast_finish: true
  include:
    - { python: "3.6", env: DJANGO=2.1 }

install:
  - pip install tox tox-venv tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV,DJANGO